front_office_homepage:
    path:     /
    defaults: { _controller: FrontOfficeBundle:Default:index }

user_main_page:
    path:     /profil/{id}
    defaults:  { _controller: FrontOfficeBundle:User:profil }
    requirements:
      id: '\d+'

show_month:
    path:     /show/{id}/{month}/{year}
    defaults:  { _controller: FrontOfficeBundle:User:show }
    requirements:
      id: '\d+'
      month: '\d+'
      year: '\d+'

add_month:
    path:     /addMonth/{id}
    defaults:  { _controller: FrontOfficeBundle:User:addMonth }
    requirements:
      id: '\d+'

delete_month:
    path:     /deleteMonth/{idMonth}
    defaults:  { _controller: FrontOfficeBundle:User:deleteMonth }
    requirements:
      idMonth: '\d+'
