front_office_homepage:
    path:     /
    defaults: { _controller: FrontOfficeBundle:Default:index }

user_main_page:
    path:     /profil/{id}
    defaults:  { _controller: FrontOfficeBundle:User:profil }
    requirements:
      id: '\d+'

edit_profil:
    path:     /editProfil/{id}
    defaults:  { _controller: FrontOfficeBundle:User:editProfil }
    requirements:
      id: '\d+'

show_month:
    path:     /show/{idMonth}/{month}/{year}/{idUser}
    defaults:  { _controller: FrontOfficeBundle:User:show }
    requirements:
      idMonth: '\d+'
      month: '\d+'
      year: '\d+'
      idUser: '\d+'

add_month:
    path:     /addMonth/{id}
    defaults:  { _controller: FrontOfficeBundle:User:addMonth }
    requirements:
      id: '\d+'

add_day:
    path : /addDay/{idMonth}/{month}/{year}/{idUser}
    defaults:  { _controller: FrontOfficeBundle:User:addDay }
    requirements:
      idMonth: '\d+'
      month: '\d+'
      year: '\d+'
      idUser: '\d+'

edit_day:
    path : /editDay/{idDay}/{idMonth}/{month}/{year}/{idUser}
    defaults:  { _controller: FrontOfficeBundle:User:editDay }
    requirements:
      idDay: '\d+'
      idMonth: '\d+'
      month: '\d+'
      year: '\d+'
      idUser: '\d+'
