back_office_homepage:
    path:     /
    defaults: { _controller: BackOfficeBundle:Default:index }

back_office_user_index:
    path:     /user
    defaults: { _controller: "WebServiceBundle:User:index" }
    methods:  GET

back_office_user_show:
    path:     /user/{id}/show
    defaults: { _controller: "WebServiceBundle:User:show" }
    methods:  GET

back_office_user_show_movement:
    path:     /user/{id}/movement
    defaults: { _controller: "BackOfficeBundle:Default:showMovement" }
    methods:  GET
    requirements:
      id: '\d+'

back_office_user_new:
    path:     /user/new
    defaults: { _controller: "WebServiceBundle:User:new" }
    methods:  [GET, POST]

back_office_user_edit:
    path:     /user/{id}/edit
    defaults: { _controller: "WebServiceBundle:User:edit" }
    methods:  [GET, POST]

back_office_user_delete:
    path:     /user/{id}/delete
    defaults: { _controller: "WebServiceBundle:User:delete" }
    methods:  DELETE

back_office_societe_index:
    path:     /societe
    defaults: { _controller: "WebServiceBundle:Societe:index" }
    methods:  GET

back_office_societe_show:
    path:     /societe{id}/show
    defaults: { _controller: "WebServiceBundle:Societe:show" }
    methods:  GET

back_office_societe_new:
    path:     /societe/new
    defaults: { _controller: "WebServiceBundle:Societe:new" }
    methods:  [GET, POST]

back_office_societe_edit:
    path:     /societe/{id}/edit
    defaults: { _controller: "WebServiceBundle:Societe:edit" }
    methods:  [GET, POST]

back_office_societe_delete:
    path:     /societe/{id}/delete
    defaults: { _controller: "WebServiceBundle:Societe:delete" }
    methods:  DELETE

back_office_service_index:
    path:     /service
    defaults: { _controller: "WebServiceBundle:Service:index" }
    methods:  GET

back_office_service_show:
    path:     /service/{id}/show
    defaults: { _controller: "WebServiceBundle:Service:show" }
    methods:  GET

back_office_service_new:
    path:     /service/new
    defaults: { _controller: "WebServiceBundle:Service:new" }
    methods:  [GET, POST]

back_office_service_edit:
    path:     /service/{id}/edit
    defaults: { _controller: "WebServiceBundle:Service:edit" }
    methods:  [GET, POST]

back_office_service_delete:
    path:     /service/{id}/delete
    defaults: { _controller: "WebServiceBundle:Service:delete" }
    methods:  DELETE
