societe_index:
    path:     /
    defaults: { _controller: "WebServiceBundle:Societe:index" }
    methods:  GET

societe_show:
    path:     /{id}/show
    defaults: { _controller: "WebServiceBundle:Societe:show" }
    methods:  GET

societe_new:
    path:     /new
    defaults: { _controller: "WebServiceBundle:Societe:new" }
    methods:  [GET, POST]

societe_edit:
    path:     /{id}/edit
    defaults: { _controller: "WebServiceBundle:Societe:edit" }
    methods:  [GET, POST]

societe_delete:
    path:     /{id}/delete
    defaults: { _controller: "WebServiceBundle:Societe:delete" }
    methods:  DELETE
